hash = {
  "Sales Person A" => { "team" => "RMS",
                        "rms_new" => 200, "rms_renewal" => 300,
                        "sccb" => 50,
                        "duntrade" => 0,
                        "cs_sub" => 0,
                        "cm_tm" => 0,
                        "seminar" => 50,
                        "s_ms" => 0,
                        "dnb_hovers" => 0 },
  "Sales Person B" => { "team" => "SCCB",
                        "rms_new" => 100,
                        "rms_renewal" => 0,
                        "sccb" => 600,
                        "duntrade" => 100,
                        "cs_sub" => 0,
                        "cm_tm" => 0,
                        "seminar" => 0,
                        "s_ms" => 500,
                        "dnb_hovers" => 0 },
  "Sales Person C" => { "team" => "RMS",
                        "rms_new" => 0,
                        "rms_renewal" => 0,
                        "sccb" => 0,
                        "duntrade" => 0,
                        "cs_sub" => 0,
                        "cm_tm" => 0,
                        "seminar" => 0,
                        "s_ms" => 500,
                        "dnb_hovers" => 200 }
}
